os: linux
language: node_js
before_script:
  - npm install -g gatsby-cli
script:
  - yarn install
  - yarn run build
deploy:
  provider: pages
  local_dir: ./public/
  token: $GH_TOKEN
  cleanup: false
  skip_cleanup: true
  edge: true
  on:
    branch: master
