os: linux
language: node_js
before_script:
  - npm install -g gatsby-cli
script:
  - yarn install
  - yarn run deploy
deploy:
  provider: pages
  local_dir: public
  cleanup: false
  edge: true
  on:
    branch: master
